// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)

void onFeedChange();
void onMaintenanceChange();
void onNoFoodChange();
void onResetWeightChange();

float weight;
CloudSwitch feed;
int reset_counter;
bool change;
bool maintenance;
bool no_Food;
bool reset_Weight;

void initProperties(){

  ArduinoCloud.addProperty(weight, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(feed, READWRITE, ON_CHANGE, onFeedChange);
  ArduinoCloud.addProperty(reset_counter, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(change, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(maintenance, READWRITE, ON_CHANGE, onMaintenanceChange);
  ArduinoCloud.addProperty(no_Food, READWRITE, ON_CHANGE, onNoFoodChange);
  ArduinoCloud.addProperty(reset_Weight, READWRITE, ON_CHANGE, onResetWeightChange);



}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
